export enum Event {
    CHANGE_STATUS = 'CHANGE_STATUS',
    AGENT_CAPTURE_SCREEN_SUCCESS = 'AGENT_CAPTURE_SCREEN_SUCCESS',
    EXAMINATION_REPORT = 'EXAMINATION_REPORT',
    AGENT_REPORT = 'AGENT_REPORT',
    COMPUTER_REPORT = 'COMPUTER_REPORT',
    ROOM_REPORT = 'ROOM_REPORT',
  }
  
  