export enum NotificationType {
    NEW_SCREEN_CAPTURE = 'NEW_SCREEN_CAPTURE',
    EXAMINATION_REPORT = 'EXAMINATION_REPORT',
    AGENT_REPORT = 'AGENT_REPORT',
    COMPUTER_REPORT = 'COMPUTER_REPORT',
    ROOM_REPORT = 'ROOM_REPORT',
  }
  